# Generated by Django 3.1.1 on 2020-09-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200927_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=10),
        ),
    ]
